services:
  - type: web
    name: ffn-to-ao3
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      npm --prefix display ci
      npm --prefix display run build
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
